mocion_index:
    path:     /
    defaults: { _controller: "AppBundle:Mocion:index" }
    methods:  GET

mocion_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Mocion:show" }
    methods:  GET

mocion_new:
    path:     /new
    defaults: { _controller: "AppBundle:Mocion:new" }
    methods:  [GET, POST]

mocion_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Mocion:edit" }
    methods:  [GET, POST]

mocion_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Mocion:delete" }
    methods:  DELETE

mocion_votar:
    path:     /{id}/show/votar
    defaults: { _controller: "AppBundle:Mocion:votar" }
    methods:  GET

mocion_lanzar:
    path:     /{id}/lanzar
    defaults: { _controller: "AppBundle:Mocion:lanzarVotacion" }
    methods: POST

mocion_mostrar:
    path:     /{id}/mostrarResultado
    defaults: { _controller: "AppBundle:Mocion:mostrarResultado" }

mocion_mostrarPresentes:
    path:     /mostrarPresentes
    defaults: { _controller: "AppBundle:Mocion:mostrarPresentes" }

mocion_extender:
    path:     /{id}/extender
    defaults: { _controller: "AppBundle:Mocion:extenderVotacion" }
    methods: POST

mocion_finalizar:
    path:     /{id}/finalizar
    defaults: { _controller: "AppBundle:Mocion:finalizarVotacion" }
    methods: POST

mocion_resultados:
    path:    /{id}/resultados
    defaults: { _controller: "AppBundle:Mocion:resultadosVotacion" }
    methods: POST
