orden_de_pago_index:
    path:     /
    defaults: { _controller: "AppBundle:OrdenDePago:index" }
    methods:  GET

orden_de_pago_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:OrdenDePago:show" }
    methods:  GET

orden_de_pago_new:
    path:     /new
    defaults: { _controller: "AppBundle:OrdenDePago:new" }
    methods:  [GET, POST]

orden_de_pago_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:OrdenDePago:edit" }
    methods:  [GET, POST]

orden_de_pago_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:OrdenDePago:delete" }
    methods:  DELETE
