proyectobae_index:
    path:     /
    defaults: { _controller: "AppBundle:ProyectoBAE:index" }
    methods:  GET

proyectobae_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ProyectoBAE:show" }
    methods:  GET

proyectobae_new:
    path:     /new
    defaults: { _controller: "AppBundle:ProyectoBAE:new" }
    methods:  [GET, POST]

proyectobae_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ProyectoBAE:edit" }
    methods:  [GET, POST]

proyectobae_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ProyectoBAE:delete" }
    methods:  DELETE

proyectobae_incorporar_a_sesion:
    path:     /{expediente}/incorporar-a-sesion
    defaults: { _controller: "AppBundle:ProyectoBAE:incorporarASesion" }
    methods:  [GET, POST]

proyectobae_incorporar_en_sesion:
    path:     /{expediente}/incorporar-en-sesion
    defaults: { _controller: "AppBundle:ProyectoBAE:incorporarEnSesion" }
    methods:  [GET, POST]